services:
  back_end:
    image: conversor/back_end:1.0
    container_name: backend
    networks:
      - web_host
    ports:
      - 8082:8082
  front_end:
    image: conversor/front_end:1.3
    container_name: frontend
    networks:
      - web_host
    ports:
      - 8081:8081
    depends_on:
      - back_end
networks:
  web_host:
    driver: bridge
